spring:
  application:
    name: payment-service

server:
  servlet:
    context-path: "/payment-service"
  port: 8082

clients:
  product-client:
    url: http://localhost:8081
    connect-timeout: 1s
    read-timeout: 30s
  limit-client:
    url: http://localhost:8083
    connect-timeout: 1s
    read-timeout: 30s
